### ISSUE TITLE
Changing the calculation device of GPU

### ISSUE THREAD

**Issue by yy-ssang** [jacobjma/abTEM#10]
There are 2 GPU on my workstation and they are different GPU each other.

So, how can I change the GPU setting to calculate in abTEM??

For example, in PyTorch which is deep learning framework, I can change GPU setting with the command like "device = 'cuda:1', device = 'cuda:0'".

Is there any command to do this in abTEM?

**Comment by jacobjma** [comment]
Hi. This will be improved in a future release, including multi-GPU parallelization. Currently you should be able to change the device by using the following command at the top of your code:
`
cp.cuda.Device(1).use()
`
where the number refers to the device id. You need to clone the latest developer version, as I just fixed a bug to make this work.

Let me know if this works or not.

**Comment by yy-ssang** [comment]
@jacobjma Oh! the command works well! thank you!
