### ISSUE TITLE
Tilt beam or specimen

### ISSUE THREAD

**Issue by yy-ssang** [jacobjma/abTEM#11]
Is there any command to tilt beam or specimen?
If no, I want to you update the function of that.
Thank you!

**Comment by TomaSusi** [comment]
Tilting the sample is done by rotating the ASE atoms object; please see its documentation here:
https://wiki.fysik.dtu.dk/ase/ase/atoms.html#ase.Atoms.rotate

Tilting the beam is not currently supported, but if you don't need to model something like a electron precession diffraction, tilting the sample should be sufficient.

**Comment by TomaSusi** [comment]
What do you think, @jacobjma, should we implement a beam tilt? It is certainly something that is experimentally used, but not sure how easy it would be to implement? Maybe on the background actually use sample tilt..?

**Comment by jacobjma** [comment]
You can do that now using the modification to the propagator function (see Eq. 6.99 in Kirklands book)
```
wave = Probe(energy=300e3, extent=10, sampling=0.04, tilt=(10,5))
```
where tilt in x and y should be given in mrad.

I think this what most people typically refer to as beam tilt, however, It may actually be more correct to call it specimen tilt, as it does not interact with parameters such as defocus (Kirkland notes this in the same section referenced above).

**Comment by TomaSusi** [comment]
Excellent, I think that's perfectly sufficient at least for now!
