### ISSUE TITLE
4D STEM simulation

### ISSUE THREAD

**Issue by CGao-STEM** [jacobjma/abTEM#12]
Dear Sir,
I tried to run the quick_4D-STEM codes to simulate a 4D dataset.  And I have a question about how to set my desired pixel numbers of Ronchigrams like (256x256, 128*128). When I had set sampling in **_potential_** function, then set gpts=(256,256) in Probe function. The results showed Ronchigrams were not (256,256). Could you help me to solve this problem?

Chuang

**Comment by jacobjma** [comment]
Hi Chuang,

abTEM uses a 2/3 antialiasing aperture described on page 145 in [Advanced Computing in Electron Microscopy](https://link.springer.com/book/10.1007/978-1-4419-6533-2). 

The output of the simulation is (256,256); however, the `max_angle` argument of the `PixelatedDetector` is set to 'valid' by default, which means that the result is cropped to the largest rectangle fitting in the antialiasing aperture.  You can change this by setting `max_angle=None,` which will give you the (256,256) result. However, the output will contain the antialiasing aperture.

To get exactly (256,256) without an antialiasing aperture, you could do a larger simulation and crop your result appropriately, there is currently not a more elegant way of doing this.

**Comment by CGao-STEM** [comment]
I see. Thanks for your reply!
Chuang
