### ISSUE TITLE
Possible bug in poisson_noise

### ISSUE THREAD

**Issue by MadsAW** [jacobjma/abTEM#13]
Thanks for the great tool in TEM image simulation.

I have currently used the tool to simulate several images, but I have now encountered an error when I attempt to add noise to these images using the ```poisson_noise``` function.
![image](https://user-images.githubusercontent.com/40065771/107572069-0a0cd880-6bec-11eb-85f2-f564ba89e694.png)

This same error occurs when running the last cell in the  ```quick_hrtem_and_saed.ipynb``` notebook provided in this repository.

I *believe* that this error occurs as the function attempts to find the sampling for the first two elements [indices 0 and 1] in the calibrations: the stack of images and x-direction. Here the sampling for the stack is a Nonetype and hence an error is returned. I believe the code function meant to look at the sampling in the x- and y-direction [indices 1 and 2] as it did before this [commit](https://github.com/jacobjma/abTEM/commit/922861b07e02dd39c034c0184e844df77397f151).

Rolling back the change done in line 175 in `abtem/noise.py` seems to solve the issue. As such I propose the following change to line 175 in order to fix the bug:

```python
pixel_area = np.product([calibration.sampling for calibration in measurement.calibrations[:2]])
->
pixel_area = np.product([calibration.sampling for calibration in measurement.calibrations[-2:]])
```

This is my best guess at why the error occurs, I hope you can tell me if I am making an error. 

Thanks again for a great tool!

**Comment by jacobjma** [comment]
Thank you for the report. This was indeed a bug introduced in the latest update. 

It should be fixed now, including the pypi version.

**Comment by MadsAW** [comment]
Perfect, thank you for the quick response!
