### ISSUE TITLE
errors happened when i tried to use segemented detecotor

### ISSUE THREAD

**Issue by xiongh15** [jacobjma/abTEM#15]
when i tried to use this to simulate dpc images by divied the detecotor into 4 parts.
dpc_detector = SegmentedDetector(inner=4,outer=22,nbins_radial=1,nbins_angular=4)
"ValueError: non-broadcastable output operand with shape (25,4) doesn't match the broadcast shape (25,25,4)"

**Comment by jacobjma** [comment]
Thank you for the report. The bug has been fixed, including in the pypi version.
