### ISSUE TITLE
Quest for help on Probe customization

### ISSUE THREAD

**Issue by xiongh15** [jacobjma/abTEM#18]
Dear author:
I have a problem with probe customization. I set the magnitude as **Å**, and angel to **mrad**

I have 2 problems:
1. the experimental semi convergence angle is 15 mrad. i tried to find how to set it but failed.
2. i listed all parameters seted in the experiment, but the CTF seems wrong. could you please help me check the code?

the parameters were attached in the bottom
the resulting ctf completely different from the expiriment
![image](https://user-images.githubusercontent.com/31976361/109095952-a3dd9500-7757-11eb-94f8-b3733d255e4f.png)

and the experimental ctf are 
![image](https://user-images.githubusercontent.com/31976361/109097450-4e56b780-775a-11eb-84b9-eaf9f7a88adf.png)

 The codes are listed as follows:
——
parameters = {
'C10':25.02, 'C12':56.78, 'phi12':27.1/180*pi*1000,                  
'C21':100.5, 'phi21':-148.1/180*pi*1000, 'C23':1073, 'phi23':-84.9/180*pi*1000,                 
'C30':5907, 'C32':3612, 'phi32':32.9/180*pi*1000, 'C34':3862, 'phi34':170.9/180*pi*1000,                 
'C41':19260, 'phi41':95.7/180*pi*1000, 'C43':32530, 'phi43':96.1/180*pi*1000, 'C45':39360, 'phi45':-112.6/180*pi*1000,                 
'C50':2570000, 'C52':747600, 'phi52':-143.8/180*pi*1000, 'C54':386300, 'phi54':32.7/180*pi*1000, 'C56':1646000, 'phi56':82.5/180*pi*1000} 

ctf = CTF(parameters=parameters, energy=300e3) 
probe = Probe(energy=300e3, semiangle_cutoff=15, ctf=ctf)
![image](https://user-images.githubusercontent.com/31976361/109095673-2ade3d80-7757-11eb-94aa-fa6742be78fa.png)
![image](https://user-images.githubusercontent.com/31976361/109095783-595c1880-7757-11eb-980a-4092739fceba.png)

**Comment by jacobjma** [comment]
Hi,

The convergence semiangle is the same as the semiangle cutoff. You can set the semiangle_cutoff parameter in the CTF.

The angles for the aberrations should be given in radians, I will make that more clear in the documentation. Other than that the parameters looks correct.

Do you have any information on how the CTF is plotted in your experimental software? The CTF is a 2d function so plotting it as a line only shows part of it. I also don't know what the two different lines correspond to. It can't be the real and imaginary part since both lines start at zero.

**Comment by xiongh15** [comment]
Dear sir. i think there is a problem in the Probe setting customized by CTF.
In order to check the functions, I  use the codes listed as follows:
It went wrong, when i use this. 
_
ctf2=CTF(defocus=50,energy=300e3) 
probe = Probe(energy=300e3,semiangle_cutoff=15,ctf=ctf2)
_
![image](https://user-images.githubusercontent.com/31976361/109168338-ad97e480-77b9-11eb-8740-0af3d699c1da.png)

it works well when i don't use CTF.
_
ctf2=CTF(defocus=50,energy=300e3) 
probe = Probe(energy=300e3,semiangle_cutoff=15,defocus=50)
_
![image](https://user-images.githubusercontent.com/31976361/109168580-efc12600-77b9-11eb-8fca-d4ea7c374ba7.png)

**Comment by xiongh15** [comment]
when I use this more straightforward way to customize the probe, it also works! but when I used CTF, it went wrong.
_
probe = Probe(energy=300e3,semiangle_cutoff=15,C10=25.02, C12=56.78, phi12=27.1/180*pi, C21=100.5, phi21=-148.1/180*pi, C23=1073, phi23=-84.9/180*pi, C30=5907, C32=3612, phi32=32.9/180*pi, C34=3862, phi34=170.9/180*pi, C41=19260, phi41=95.7/180*pi, C43=32530, phi43=96.1/180*pi, C45=39360, phi45=-112.6/180*pi, C50=2570000, C52=747600, phi52=-143.8/180*pi, C54=386300, phi54=32.7/180*pi, C56=1646000, phi56=82.5/180*pi)
