### ISSUE TITLE
ctf

### ISSUE THREAD

**Issue by geoffwoollard** [jacobjma/abTEM#2]
I'm struggling with the ctf terminology you are using. I think there is different lingo in materials science communities vs life science cryoEM communities.

I am used to the formulation in these resources
https://pubmed.ncbi.nlm.nih.gov/26278980/ (introduction of this paper, a commonly software program to fit the ctf)
https://github.com/asarnow/pyem/blob/master/pyem/ctf.py
https://en.wikipedia.org/wiki/Contrast_transfer_function

Could you please point me to a reference? I'm more familiar with spatial frequency (k-space). How do I convert `alpha` and `semiangle_cutoff` to this?

**Comment by geoffwoollard** [comment]
These lines in `waves.Waves.apply_ctf` are helping:

```
        kx, ky = spatial_frequencies(self.grid.gpts, self.grid.sampling)
        alpha, phi = polargrid(xp.asarray(kx * self.wavelength), xp.asarray(ky * self.wavelength))
```

**Comment by geoffwoollard** [comment]
Just saw this https://github.com/jacobjma/abTEM/blob/master/docs/source/walkthrough/05_contrast_transfer_function.ipynb

It's very helpful thanks!

**Comment by geoffwoollard** [comment]
For maximum semiangle allowed, there is a good discussion in E. Kirkland (2020) "Advanced Computing in Electron Microscopy" p 115. I noticed that ref in your code.

**Comment by TomaSusi** [comment]
Thanks for the comments! Indeed the walkthrough was meant to clarify this, do you have any remaining questions?

**Comment by jacobjma** [comment]
Hi Geoff,

Thank you for raising this. The issue should be resolved in the latest version.

**Comment by geoffwoollard** [comment]
I found the discussion in Kirkland very helpful. Thanks for including that ref.

**Comment by jacobjma** [comment]
I was a bit hasty closing this. Did you figure out the discrepancy? It could be good to have a guide for the cryoEM community.

We follow the Kirkland reference, which is the standard reference for TEM simulation in materials science.

**Comment by geoffwoollard** [comment]
You already have good short hand for `Cs` and `defocus`. The semiangle_cutoff was not familiar for me. 

I would suggest you add in the following note somewhere for cryoem life science users for semiangle_cutoff (from Kirkland, p. 55,115): `semiangle_cutoff (mrad) = electron wavelength * spatial frequency * 1000`: determines the spatial frequency, after which the aperture function sets the transfer function to zero.

So a typical CTF in cryoEM applications (energy 300 eV, Cs 2mm, defocus 2.5 um), up to 2 A spatial frequency would be
```
from abtem.transfer import CTF
ctf = CTF(defocus=2.5e4, # 2.5 um
          Cs=2e7, # 2 mm
          energy=3e5 # 300 kV
          )
k = 1/2 # up to 2 A, in A-1
lam = wave.wavelength # ~1.97 pm for 300 kV, in A
semiangle_cutoff = k*lam*1000 # in mrad
ctf.show(semiangle_cutoff=semiangle_cutoff)
```

I closed the issue.
