### ISSUE TITLE
"Atoms are not orthogonal" error

### ISSUE THREAD

**Issue by Chuqiao2333** [jacobjma/abTEM#21]
Hi Jacob,

I am trying to build the TEM simulation of the Ag (111) plane following your walkthrough scripts. However, I find an error when I want to get the potential. The program shows that the Ag (111) plane is not orthogonal. I am not sure how to deal with this. Should I cut the atom plane to a rectangular?

Here are the shape of Ag (111) plane and the error in the code.

<img width="1087" alt="Screen Shot 2021-03-30 at 9 11 52 AM" src="https://user-images.githubusercontent.com/53119502/112918666-f8e63f80-9137-11eb-94d5-43b2c45edfea.png">
<img width="1077" alt="Screen Shot 2021-03-30 at 9 12 18 AM" src="https://user-images.githubusercontent.com/53119502/112918682-08658880-9138-11eb-8a4d-2f4e9b8e43b3.png">

**Comment by TomaSusi** [comment]
As you may have noticed, abTEM requires orthogonal unit cells. However, there's a handy utility for that, which is documented in the first walkthrough:
https://abtem.readthedocs.io/en/latest/walkthrough/01_atomic_models.html
