### ISSUE TITLE
orthogonalize_cell() repeats structure unnecessarily (?)

### ISSUE THREAD

**Issue by TomaSusi** [jacobjma/abTEM#23]
For typical graphene hexagonal unit cells, using orthogonalize_cell() with default parameters results in an orthogonal cell that seems to me is unnecessarily 2x repeated in the y direction (see attached for an visualization).

Am I mistaken? Would it not be possible to take half of the orthogonal cell in y instead?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/66075496/115689778-afff6080-a35c-11eb-942b-f5fdb6b6658c.png">

**Comment by jacobjma** [comment]
I think the function does what it is supposed to.

If you tile the hexagonal cell and the orthogonal cell, you will get the same structure. If you half the orthogonal unit cell it would not repeat in the same pattern as the hexagonal cell.

**Comment by TomaSusi** [comment]
Ah yes, you mean that the periodic arrangement of the images will be faithfully reproduced? Yes, I see what you mean.

However, often one does not really don't care about that and is using the unit cell as a proxy for an infinite structure. In this case, I would like an option to orthogonalize to a minimal corresponding cell.

**Comment by jacobjma** [comment]
Yes. In this case, you probably get the structure you want using
```
atoms.cell[1,0] = 0
atoms.wrap()
```
However, this is a different structure, and it only makes sense in certain cases. For example, you cannot do this to the minimal hexagonal structure, it will no longer be hexagonal when repeated.

**Comment by TomaSusi** [comment]
Right... hmm. I can confirm that gets me there.

It's just a situation that I run across repeatedly, but maybe there is no sense in making any change to the function to accommodate that.

**Comment by jacobjma** [comment]
It could be an option, but I don't think it should be default behavior. There is also the `cut_rectangle` function, which simply cuts out a rectangle from a unit cell, repeating the structure if the rectangle is larger than the cell. 

I believe the code below also gives you the correct structure.
`
atoms = cut_rectangle(atoms, origin=(0,0), extent=np.diag(atoms.cell)[:2])
`

**Comment by TomaSusi** [comment]
Yeah not default behavior, but I think it might be nice to have an option that uses the cut_rectangle function internally. Your code works but I do have to modify the extent to 
`extent=np.diag(atoms.cell)[:2]/[1,2]`

**Comment by jacobjma** [comment]
We could have an `enforce_periodicity` argument which is true by default, but if it false, it will just make the structure orthogonal with no insurance of preserving the original periodic repetition.

**Comment by TomaSusi** [comment]
Hmm... it's maybe a little bit of a misnomer, since any results must be periodic.

How about `preserve_periodicity`?

**Comment by jacobjma** [comment]
Yeah, that is better.

**Comment by TomaSusi** [comment]
If the argument is implemented, please close the issue!

**Comment by jacobjma** [comment]
A preserve_periodicity argument have been added to the orthogonalize_cell function

**Comment by TomaSusi** [comment]
I tried this out for the first time today, and it works fine – but only if I first do atoms.center(). Might we consider adding that by default when `preserve_periodicity = False`? @jacobjma
