### ISSUE TITLE
Differing coordinate syntax for interpolate_line() vs. plt.plot()

### ISSUE THREAD

**Issue by TomaSusi** [jacobjma/abTEM#24]
The abTEM interpolate_line() function accepts coordinate arguments in the form
`interpolate_line(start = (x1, y1), end = (x2, y2))`
while to plot a line in matplotlib, the plotting arguments are instead
`plot(x, y)`,
which for a horizontal line would use `x = (x1, x2), y = (y0, y0)` and for a vertical one `x = (x0, x0), y = (y1, y2)`.

This can often result in a hassle for the user where they have to denote the same coordinates in two different ways for this commonly used functionality (create and plot a line profile).

Would it still be possible to harmonize the interpolate_line() syntax with the matplotlib syntax? We'd have to fix a couple of examples, but I think it would be worth it. Or would it conflict with some other conventions in abTEM?

**Comment by jacobjma** [comment]
It does clash a bit with the convention used for the scan objects. Which I think is preferable for them at least, since we can things like 
```
GridScan(start=(0,0), end=potential.extent)
```
I don't mind changing it, although sometimes the new way could be less convenient, for example, if you want to interpolate a line between two atoms.

**Comment by TomaSusi** [comment]
Right hmm the GridScan is denoted in that way... I wonder if instead we could make an abTEM-native way to display the overlaid line profiles in sync with how we use the interpolate_line() function? That would also solve the problem.

**Comment by TomaSusi** [comment]
There is actually another issue that could potentially be addressed at the same time: very often one wishes to draw a line profile over an atom, while the atomic coordinates one receives from ASE obviously denote only the x,y position of the atom itself. While for horizontal and vertical line profiles, one can relatively easily define line profile endpoint coordinates with ±offset, this gets complicated when the angle of the line is not 0, 45 or 90 degrees.

Thus for the user it would be great if one could simply specify the two atoms over which one wants the line profile to be drawn, and the there would be in-built functionality to move the endpoints of the line to start before/end after the given atom position by some reasonable value which could have a default of, say, 1 Å, but also be user-definable via an `offset` parameter.

**Comment by TomaSusi** [comment]
Here's an example of code I've been writing to do this in general, which could certainly be more elegant (and actually fails for one of my cases since the angle is 30 degrees):

`x4_1 = atomsAlC3N[atN1].position[0]
x4_2 = atomsAlC3N[atC1].position[0]
y4_1 = atomsAlC3N[atN1].position[1]
y4_2 = atomsAlC3N[atC1].position[1]

x3_1 = atomsAlC2N[atN2].position[0]
x3_2 = atomsAlC2N[atC2].position[0]
y3_1 = atomsAlC2N[atN2].position[1]
y3_2 = atomsAlC2N[atC2].position[1]

d = 1.0

xc4 = (x4_1-d, x4_2+d)
yc4 = (y4_1-d, y4_2+d)

xc3 = (x3_1-d, x3_2+d)
yc3 = (y3_1-d, y3_2+d)

start4 = (x4_1-d, y4_1-d)
end4 = (x4_2+d, y4_2+d)

start3 = (x3_1-d, y3_1-d)
end3 = (x3_2+d, y3_2+d)

l_adf_4 = measAlC3N.interpolate_line(start4, end4, sampling = 0.04)
l_adf_3 = measAlC2N.interpolate_line(start3, end3, sampling = 0.04)

...

axes[0].plot(xc4, yc4)
axes[1].plot(xc3, yc3)`

**Comment by jacobjma** [comment]
We could use that the scan objects can be plotted
```
line_measurement, line_scan = measurement.interpolate_line(start = (x1, y1), end = (x2, y2), return_line_scan=True)

...

line_scan.add_to_mpl_plot(ax)
```
Alternatively, the method could receive an mpl axis and do the plot, but then the figure has to be created above the interpolation.


For the second question, maybe just having an `interpolate_line_across` method would work. It could take an atom or a position, an offset and angle, and just call `interpolate_line` under the hood.
```
line_measurement = measurement.interpolate_line_across(atoms[5], offset=1, angle=30)
```

**Comment by TomaSusi** [comment]
Hmm.. in the first case, the problem is still that one has to define the endpoints by hand, instead of having an easy way to get them from the ASE atoms object. Also, I think it is more common that one measures a 2D scan, but then wants to plot certain line profiles over it, instead of doing a line measurement just for that purpose.

As for `interpolate_line_across`, that sounds fine (as long as `atoms[5]` can be two different atoms).

**Comment by jacobjma** [comment]
The issue with using the `line_measurement` is that currently all measurements are just instances of the general `Measurement` class, and having a start and endpoint does make sense for all measurements.

I have been thinking about implementing more specialized measurement classes
* LineProfile
* Image
* DiffractionPatterns
* FlexibleAnnularMeasurement

This would also solve the issue of having special methods for some types of measurements, that does not make sense for others.

I could start with implementing a line profile class for now, which would keep track of start and endpoints and have a method for plotting it.

**Comment by TomaSusi** [comment]
Okay, I see. Probably a separate LineProfile class is then the best solution. In some sense one could argue that it's not "our responsibility" to implement things that can be done with standard python and matplotlib code, but since this is a very often used case, I think making it super simple for the user is worth it.

**Comment by jacobjma** [comment]
This is now working. It is implemented in the `interpolate_line` method rather than creating a new method. 

The endpoint is now an optional parameter. However, if the endpoint is not given, you should provide the margin parameter, which will extend the line on both sides of the line. Both start and end can be given as an Atom; the margin parameter can also be used when the endpoint is given.

```
line1 = measurement.interpolate_line(atoms[3], margin=1., angle=30)
line2 = measurement.interpolate_line(atoms[16], margin=1., angle=30)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

measurement.show(ax=ax1)

line1.add_to_mpl_plot(ax1, color='r')
line2.add_to_mpl_plot(ax1, color='lime')

line1.show(ax=ax2, color='r', label='Mo')
line2.show(ax=ax2, color='lime', label='S2')

ax2.set_ylabel('Intensity [arb. unit]')
ax2.legend();
```

**Comment by TomaSusi** [comment]
This works great for real-space measurements, thanks!

But is there a good solution for diffraction patterns? Obviously atom indices cannot be used there, but can we avoid defining the endpoints in two different ways in that case?

**Comment by TomaSusi** [comment]
Ah no I am being silly, of course the same syntax works, I just need to define the reciprocal space positions by hand in the first instance!

**Comment by TomaSusi** [comment]
All right, I'd say we can close this.
