### ISSUE TITLE
orthogonalize_cell() requires exactly orthogonal axes

### ISSUE THREAD

**Issue by drpaulsharp** [jacobjma/abTEM#25]
I have results results of simulations which give me unit cells with angles between 89 and 91 degrees, which are rejected by orthogonalize_cell() because there is no vertical lattice vector (with the 1e-12 tolerance) despite the fact that the unit cell is almost orthogonal. Can orthogonalize_cell() be adapted to make these almost orthogonal unit cells exactly orthogonal?

**Comment by TomaSusi** [comment]
Hi! What do you mean by "no vertical lattice vector"? Surely you need to have three lattice vectors, one of them vertical..?

**Comment by jacobjma** [comment]
@TomaSusi not necessarily, you can rotate the cell so no lattice vector points exactly along the z-direction.

@drpaulsharp The orthogonalize_cell only "orthogonalizes" in the xy-plane, i.e. you have to make sure that your input cell  have one lattice vector perpendicular with z. 

The more fundamental issue is that the orthogonalize_cell function expand the cell to make it orthogonal while preserving periodicity exactly. This is not just a question of changing lattice vectors, in fact small rotations are more challenging as they typically require a gigantic cell. 

For small rotations, I would say one degree is at the limit, depending on the size of your cell. Rotations can be incorporated in the Fresnel propagator. In abTEM, this can be triggered by setting the tilt argument of the `Probe`, `PlaneWave`and `SMatrix` objects. For example (tilt in mrad)
```
probe = Probe(extent=10, sampling=.05, energy=80e3, tilt=(20,20))
```

The other soultion is to avoid making the cell periodic. This would require expanding the cell enough that you have a scan region where none of the probes feel the edge of the cell. I could make an example of this, as it is probably an often encountered issue.

**Comment by drpaulsharp** [comment]
@jacobjma Yes, this ties in with my experience, trying to make some of these unit cells orthogonal whilst preserving periodicity has resulted in extremely large cells.

If you could produce an example of an expanded cell such that the probes do not feel the edges, it would be very useful. Thanks very much.

**Comment by jacobjma** [comment]
@drpaulsharp I added this [example](https://github.com/jacobjma/abTEM/blob/master/examples/other/simulating_non-periodic_structures.ipynb). It will need some more work, however, maybe you could have a look now and give me some feedback.

**Comment by drpaulsharp** [comment]
@jacobjma Thanks very much for this example, it's very helpful and seems to solve my problem.

There is a bug on the line starting "repetitions_xy = . . ." - this variable is referred to as "reps_xy" afterwards in the code.

I am able to follow the code example for the example file, however, when using my own results the potential still rejects them on the grounds that the unit cell is not orthogonal. Therefore, I have reset the unit cell as an orthogonal cell surrounding the new (larger) set of atoms, i.e, after expanding the Atoms object I have added:

```
max_coords = np.matmul(atoms.cell, [1.0, 1.0, 1.0])
atoms.set_cell(max_coords)
```

which enables the code to run and output an image for my results. This addition seems ok to me, can you see it causing any problems?

**Comment by jacobjma** [comment]
@drpaulsharp I fixed the bug.

I am not quite sure why you would get that error. Does the cell start orthogonal and then you rotate it? In that case, maybe the issue is that `rotate_cell=True`. 

If you are importing the structure, could you share an example, I can look at?

**Comment by drpaulsharp** [comment]
The reason is that in the example, the unit cell is expanded and rotated to ensure that the a-b plane of  the unit cell is perpendicular to the z axis, but the angles between the unit cell axes do not change, and abtem uses those parameters to determine orthogonality, rather than the orthogonal scan region. I've attached an example structure which should illustrate this.

[Fe3O4.zip](https://github.com/jacobjma/abTEM/files/6560244/Fe3O4.zip)

**Comment by jacobjma** [comment]
Right, the addition you came up with should be fine. I will have to think about making this more intuitive.

I modified the notebook as well [simulating_non-periodic_structures.zip](https://github.com/jacobjma/abTEM/files/6560399/simulating_non-periodic_structures.zip)

**Comment by TomaSusi** [comment]
Can we close this @drpaulsharp?

**Comment by drpaulsharp** [comment]
Yes, I think we're sorted.
