### ISSUE TITLE
How to use a 48 core server for abTEM

### ISSUE THREAD

**Issue by w-markus** [jacobjma/abTEM#26]
Dear all,

first of all, thanks a lot for this nice software!

I have a HP proliant server at hand, providing 48 cores. Unfortunately abTEM seems to use only one core. Is there a way to make them all work?

Best wishes
Markus

**Comment by jacobjma** [comment]
Thanks for the report.

Yes, abTEM is currently not well optimized for multi-CPU systems, since our focus has been on GPU parallelization. We are currently working on parallelizing using Dask. Optimistically I could share an experimental version within the next couple of weeks if you like.

I am still very surprised that only one core is used. What simulation are you doing?

abTEM uses pyFFTW under the hood, which does multithreaded parallelization. Could you run the script below on your system? On my 8-core desktop system, it engages all cores 100% (once it reaches the loop).

```
import pyfftw
import numpy as np

FFTW_EFFORT = 'FFTW_MEASURE'
FFTW_THREADS = 16

array = np.random.rand(4096,4096) + 1.j * np.random.rand(4096,4096)

dummy = pyfftw.byte_align(np.zeros_like(array))

pyfftw.FFTW(dummy, dummy, axes=(-1, -2), threads=FFTW_THREADS,
            flags=(FFTW_EFFORT, 'FFTW_DESTROY_INPUT'),)

fftw_forward = pyfftw.FFTW(array, array, axes=(-1, -2),
                           threads=FFTW_THREADS,
                           flags=(FFTW_EFFORT, 'FFTW_WISDOM_ONLY', 'FFTW_DESTROY_INPUT'))

print('start looping')
for i in range(1000):
    fftw_forward()
```

**Comment by w-markus** [comment]
I just tried both variants, i.e. as a python script on its own and within an jupyter notebook. In either case only one python process is used.

When playing around with this multicore machine I found it quite easy to engage ipyparallel for parallel computations Using abTEM I am doing some CBED simulations.

**Comment by TomaSusi** [comment]
Maybe @w-markus you could post your script just to double-check it is correct?

**Comment by w-markus** [comment]
well, I did copy and paste. :-)

Not only the example above, but also the things I was trying were just copied from the abTEM documentation.

**Comment by jacobjma** [comment]
The issue must be in pyFFTW then. You could try posting there as well.

What is your CPU model? What OS are you using? Which numpy config do you have (MKL or BLAS)?
```
import numpy as np
np.show_config()
```

The dot product in NumPy should also be multithreaded. To debug further, you could try:
```
import numpy as np
array = np.random.rand(8096, 8096)

for i in range(100):
    np.dot(array, array)
```
I get around 75 % utilization on my hardware.

**Comment by w-markus** [comment]
Our server is a
HPE ProLiant DL385 Gen10, 2x Epyc 7F72, 512 GB RAM

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'lapack', 'blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/local/include', '/usr/include']
```
A lot of libraries are missing, though I installed quite a lot which from their name sounded suitable, but obviously not working.

OS is Debian/testing.

**Comment by w-markus** [comment]
BTW: libertem seems to take advantage of all cores. :-)

**Comment by jacobjma** [comment]
Cozy setup. I suppose the fact that your hardware is quite new may be why pyFFTW have not caught up. Raising an issue could help, but pyFFTW is criminally understaffed. 

As mentioned, we are moving towards using Dask, which will mostly remove this issue for you. libertem also uses Dask; in fact, we decided on using Dask after a discussion with the creators of libertem. 

As mentioned above, I could have an experimental version ready in a few weeks.

I would still encourage you to create an issue with pyFFTW.

**Comment by w-markus** [comment]
I raised the issue at [pyFFTW](https://github.com/pyFFTW/pyFFTW/issues/315), but it seems that I have to deal with the situation as it is, as long as threading is used for parallelization. :-(

**Comment by jacobjma** [comment]
Yeah, multithreading is the only option for parallelizing the FFT algorithm. If you can't do multithreaded FFT's, there must be other programs using FFTW lagging as well (e.g. GPAW).

I would be interested in seeing how your system performs on the FFT convolution speed test attached below, it is testing all the Python implementations of the FFT algorithm I know of. On my system, Intel's MKL and PyFFTW are neck and neck, the serial NumPy implementation is _much_ slower. I would predict PyFFTW outperforms MKL on an AMD system.

You need to use conda to install MKL.  
```
conda install -c conda-forge mkl_fft
```

![fft_speed_test](https://user-images.githubusercontent.com/17334286/120466926-e8547e80-c39f-11eb-8d6d-7251e0622675.png)
[fft_convolution_speed_test.zip](https://github.com/jacobjma/abTEM/files/6583835/fft_convolution_speed_test.zip)

**Comment by w-markus** [comment]
Well, this looks not as good as above:

![image](https://user-images.githubusercontent.com/17848481/120487683-76d3fa80-c3b6-11eb-82c6-690d41cf0dd9.png)

no idea, whether this plays a role, but above was obtained without cores started in IPython Clusters, in the diagram below 48 cores were started.

![image](https://user-images.githubusercontent.com/17848481/120488023-b8fd3c00-c3b6-11eb-8e0c-688c0498ec69.png)

**Comment by jacobjma** [comment]
Thanks for running the tests. Yeah, I would certainly expect your system to perform better than my desktop. I honestly don't know what is going on.

Thanks for the interesting link, I was not aware of that project, and it was very informative. However, it is mainly another python wrapper for FFTW and similar codes, they do support the MPI version FFTW, however, for the sizes, we typically need (rarely up to 8x8k) distributed FFT's are not needed on modern hardware.

I should not have said that threading is the only way to parallelize the FFT algorithm. Obviously, a batch of FFTs can be distributed along the batch dimension, additionally, a 2d FFT can be decomposed into 1d FFT and distributed, however, it requires redistributing memory in the middle to calculate the FFT's along the second direction. On my system, FFTW-MPI, is much slower than threads and not necessary for an 8x8k, or smaller, calculation. 

As I said, we are working on implementing Dask. I don't think I can help you much more before that is done.

The following code uses distributed parallelization with Dask along the batch dimension, so It should utilize your system, right? You can tweak the parameters a bit.
```
import numpy as np
import dask.array as da

resolution = 4096
n_transform = 32

array = da.random.random((n_transform, resolution, resolution), chunks=(1, resolution, resolution))
np.fft.fft2(array).compute()
```

**Comment by w-markus** [comment]
I did some parallel calculations using ipyparallel. Something like:

```

import ipyparallel as ipp
clients  = ipp.Client()
view = clients[:]
print(clients.ids)

# some code to produce a list of potentials
# where each potentials item may contain several potentials, e.g. from frozen phonon configurations

def _multislice(potential):
    from abtem.waves import PlaneWave

    wave = PlaneWave(energy=200e3, sampling=0.25)
    exit_wave = wave.multislice(potential)
    return exit_wave

exit_waves = view.map(_multislice, potentials).get()
```
Now, I want to bring all resulting diffraction patterns together:
```
from abtem.measure import Measurement
dps = ew.diffraction_pattern('valid', block_zeroth_order=True)
print(dps)
for ew in exit_waves[1:]:
    dps= np.vstack((dps.array, ew.diffraction_pattern('valid', block_zeroth_order=True)))
    print(dps)
    dps = Measurement(array=dps)
    print(dps)
ax, im = dps.mean(axis=0).show(power=.125, figsize=(16,16), cmap='jet')

ax.set_xlim([-20,20])
ax.set_ylim([-20,20])
plt.show()
```
Does not work:

```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

~/Software/abTEM/abtem/measure.py in mean(self, axis)
    452             A measurement with the same shape, but with the specified axis removed.
    453         """
--> 454         return self._reduction(np.mean, axis)
    455 
    456     def intensity(self):

~/Software/abTEM/abtem/measure.py in _reduction(self, reduction_function, axis)
    415             axis = (axis,)
    416 
--> 417         array = reduction_function(self.array, axis=axis)
    418 
    419         axis = [d % len(self.calibrations) for d in axis]

<__array_function__ internals> in mean(*args, **kwargs)

/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
   3370             return mean(axis=axis, dtype=dtype, out=out, **kwargs)
   3371 
-> 3372     return _methods._mean(a, axis=axis, dtype=dtype,
   3373                           out=out, **kwargs)
   3374 

/usr/lib/python3/dist-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    158             is_float16_result = True
    159 
--> 160     ret = umr_sum(arr, axis, dtype, out, keepdims)
    161     if isinstance(ret, mu.ndarray):
    162         ret = um.true_divide(

TypeError: unsupported operand type(s) for +: 'float' and 'Measurement'
```

I check, that ``` dps``` is a Measurement object.

**Comment by w-markus** [comment]
found the trick:

```
from abtem.measure import Measurement

dps = exit_waves[0].diffraction_pattern('valid', block_zeroth_order=True)
for ew in exit_waves[1:]:
    dps= np.vstack((dps.array, ew.diffraction_pattern('valid', block_zeroth_order=True)))
    dps = Measurement(array=dps, calibrations=dp.calibrations, units=dp.units)

ax, im = dps.mean(axis=0).show(power=.125, figsize=(16,16), cmap='jet')
...
```
