### ISSUE TITLE
apply_ctf not updating array

### ISSUE THREAD

**Issue by geoffwoollard** [jacobjma/abTEM#3]
Once I do apply_ctf, how should I get at the updated array values? This is how I'm doing it. I can't seem to apply the ctf.

I cloned the github repo today. I'm actually pip installing to get all the dependencies (ase) and then putting the abtem folder from the github repo where pip does).

```
exit_wave = PlaneWave(energy=300e3,sampling=.3).multislice(potential)
ewa = exit_wave.array.copy() # save for comparison later

ctf = CTF(defocus=2.5e4, # 2.5 um
          Cs=2e7, # 2 mm
          energy=3e5 # 300 kV
          )
exit_wave.apply_ctf(ctf)

ewa_ = exit_wave.array.copy()
np.allclose(ewa,ewa_) # returns True, so the ctf wasn't applied
```

Maybe there's some issue with overwrite_x etc

**Comment by jacobjma** [comment]
Hi Geoff,

This is currently intended behavior: `.apply_ctf` returns a copy with the CTF applied, it does not modify the original wave.

```python
exit_wave = PlaneWave(energy=300e3,sampling=.3).multislice(potential)
ewa = exit_wave.array.copy() # save for comparison later

ctf = CTF(defocus=2.5e4, # 2.5 um
          Cs=2e7, # 2 mm
          energy=3e5 # 300 kV
          )
image_wave = exit_wave.apply_ctf(ctf)

ewa_ = image_wave.array.copy()
np.allclose(ewa,ewa_) # False
```

Perhaps the behavior you expected is better, I have not decided yet. At least I will try to make it more clear.

**Comment by geoffwoollard** [comment]
Oh I see it returns the ctf convoluted array.

I think you should keep it as is. It's good to have the original one
