### ISSUE TITLE
1)	How can we define the grid size of atoms manually?

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#32]
1)	How can we define the grid size of atoms manually, if (wave.multislice) automatically adopts the grid size itself??

**Comment by TomaSusi** [comment]
I'm not sure I understand correctly by what you mean by the "grid size of atoms" – to control the sampling of the scattering potential, we use the parameter `sampling`.

**Comment by TomaSusi** [comment]
Does this answer your question, @hkazmi25 ?
