### ISSUE TITLE
3)	If I wanted to remove any (one) layer of atoms (or slice) from multislice 

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#33]
3)	If I wanted to remove any (one) layer of atoms (or slice) from multislice , How can I do that.

**Comment by TomaSusi** [comment]
This does not sound like something one should be doing. You should remove the layer of atoms from the atoms object BEFORE you build the potential, and then the multislice will automatically reflect the changed atomic structure.

You can find some instructions on how to manipulate the atoms object on the ASE wiki pages:
https://wiki.fysik.dtu.dk/ase/gettingstarted/manipulating_atoms/manipulating_atoms.html
