### ISSUE TITLE
 change the thickness of slices/ control the number of slices

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#34]
if we wanted to change the thickness of slices/ control the number of slices, can you provide a little guide line on it. I was reading the abTem manipulation section, but didn’t understood.

**Comment by jacobjma** [comment]
You can select whatever slice thickness you like. If that is unclear, please let us know how to improve it.
```
# potential with 2 angstrom slice thickness
potential = Potential(atoms, slice_thickness=2) 
```
