### ISSUE TITLE
Problem running the program

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#35]
File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: The specified procedure could not be found.

I created a new environment of abtem, I installed by using pip install abtem.. I install h5py as well. i can see everything is perfectly install in my computer when i find the conda list abtem .. but still i am getting this error.

**Comment by TomaSusi** [comment]
Which versions of hdf5 and h5py are you using?

**Comment by jacobjma** [comment]
I have seen this error before. You can search for "python hdf5 DLL load failed".

I believe this will work to create a functional abTEM env on windows:
```
conda create -n abtem python=3.8
conda activate abtem
conda install anaconda
pip install abtem
```
Let us know if it does not work.

**Comment by jacobjma** [comment]
This is a useful issue as I believe many windows users will face the same problem. So I should create a common issues section in the install instructions.

**Comment by hkazmi25** [comment]
So i tried almost everything i know to my limited knowledge. It doesn't work in windows.  install, reinstalled from scratch. the error now i am struggling with is  \h5py> python .\setup.py build.. 

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I did install C++ 14.0 ... and greater as well, restarted my many time computer but still the problem continues.  I know windows sucks. :(

**Comment by jacobjma** [comment]
Your issue seems to be with hdf5 for python, which is a very common package in electron microscopy and works on windows.

To see if this really does not work you could create a new env and install h5py
```
>>> conda create -n h5py_test python=3.8
>>> conda activate h5py_test
>>> conda install h5py
```

Open python and test it:
```
>>> python
>>> import h5py
```
Let me know if this works.

**Comment by TomaSusi** [comment]
@hkazmi25 could you please give us feedback on whether this instruction helped you?

**Comment by jacobjma** [comment]
I am closing this. Please reopen if you still have this issue.
