### ISSUE TITLE
Simulation on 'discrete' systems like nanoparticles/clusters

### ISSUE THREAD

**Issue by SnehaRV** [jacobjma/abTEM#36]
Thanks for sharing the really nice program and examples. I am running test examples and find that it works great for 'periodic' systems. How to go about simulating for discrete systems? Any example notebooks available? For example, how to simulate HAADF image from the Cu nanoparticle example given in ASE. 

#surfaces = [(1, 0, 0), (1, 1, 0), (1, 1, 1)]
#layers = [6, 9, 5]
#lc = 3.61000
#atoms = FaceCenteredCubic('Cu', surfaces, layers, latticeconstant=lc)

ps: I am new to ASE and python and still figuring my way around

**Comment by TomaSusi** [comment]
Thanks, glad you like it!

There's no great difference between periodic and discrete systems – if you define for example a nanoparticle structure in the center of a vacuum cell in ASE, you can use that just in the same way as a periodic structure.

**Comment by jacobjma** [comment]
We have example notebooks for STEM and one for HRTEM for simulating nanoparticles. We don't have exactly what you want, but as this may be a common use case I put it together below; how I would do it.

Let us know which parts are difficult to understand, and don't use the code without understanding what it does.

Create Wullf constructed nanoparticle:
```
from ase.io import read
from ase.cluster import wulff_construction
from ase import Atoms
import matplotlib.pyplot as plt

from abtem import *

surfaces = [(1, 0, 0), (1, 1, 0), (1, 1, 1)] # Nanoparticle facets

esurf = [1.0, 1.1, 0.9] # Relative surface energies

size = 200 # Target number of atoms

atoms = Atoms(wulff_construction('Au', surfaces, esurf, size, 'fcc', rounding='above'))

atoms.center(vacuum=5)

atoms.rotate(45, 'x', center='cop')
```
Create potential (for production you need to use frozen phonons, the commented code)
```
#frozen_phonons = FrozenPhonons(atoms, num_configs=32, sigmas=.1)
#potential = Potential(frozen_phonons, parametrization='kirkland', projection='infinite')

potential = Potential(atoms, parametrization='kirkland', projection='infinite')
```
Run computation
```
detector = AnnularDetector(50, 150)

probe = Probe(energy=80e3, semiangle_cutoff=20, sampling=.05, device='cpu')

gridscan = GridScan(start=[0, 0], end=potential.extent, sampling=probe.ctf.nyquist_sampling * .9) 

measurement = probe.scan(gridscan, detector, potential)
```
Interpolate to desired sampling frequency and get the result
```
interpolated_measurement = measurement.interpolate(.05)
interpolated_measurement.array
```

Running the code takes 5 min on my computer.

**Comment by SnehaRV** [comment]
Thanks very much. That was really helpful

**Comment by TomaSusi** [comment]
Let us know if this works for you, and please close the issue if it does :)

**Comment by SnehaRV** [comment]
Yes, works great. Thank you very much once again for sharing this really useful program..
