### ISSUE TITLE
How can we show potential image in a log scale?

### ISSUE THREAD

**Issue by fzhuseux** [jacobjma/abTEM#38]

**Comment by jacobjma** [comment]
The potential can go to zero so a log scale may not be the best choice. You can use a power scale like this:
```
measurement = potential.project()
measurement.show(power=.1)
```
If you insist you can get a log scale like this:
```
measurement = potential.project()
measurement.show(log_scale=True)
```
You can also get the projected potential array as so:
```
measurement = potential.project()
measurement.array
```
and then plot it however you like.
