### ISSUE TITLE
latest release on pypi

### ISSUE THREAD

**Issue by ericpre** [jacobjma/abTEM#39]
The latest tag is not available non pypi, would it be possible to upload the latest tag on pypi? Once, it is on pypi, the conda-forge bot will create a PR to update the feedstock.

On a similar topic, would you be interested in setting a github workflow to automate the release process? We have been using these for various packages and it works very well, see for example https://github.com/hyperspy/hyperspy_gui_ipywidgets/blob/master/.github/workflows/release.yml
and a corresponding CI run: https://github.com/hyperspy/hyperspy_gui_ipywidgets/actions/runs/745309960

I can make a PR with the relevant documentation, etc.

**Comment by jacobjma** [comment]
Thanks for the reminder, it should be available now. 

I actually bumped the version and created a new release to get some new developments in (mainly EELS).

We have been really bad at releases until now, with the recent increase in attention, we should get much better at that. I would be grateful to take any help in improving the release process. I admit that I don't know how all the things you mentioned works, but I will read up on it, if you create a PR.

**Comment by ericpre** [comment]
Sorry, I think that I was confused by the versioning when looking for the 1.0.022 version, which I expected from the tags at https://github.com/jacobjma/abTEM/tags!

The issue with the conde-forge bot may be that "pre-release" versions are filtered out - this or the presence of `b` in the version.

**Comment by jacobjma** [comment]
Oh, okay. We have been inconsistent with using the proper prerelease tag, however, all versions so far should have used a "b" or "beta" in the version number.

**Comment by ericpre** [comment]
Actually, the correct reason that the conda-forge bot didn't make a PR may be that only the wheel was uploaded to pypi and not the source distribution.

**Comment by jacobjma** [comment]
Sorry, about the sluggishness, I really appreciate this issue.

I merged the pull request, and added the PyPI secret. So that should work now.

abTEM is pure python, so I would have thought that uploading the wheel is good enough?

**Comment by ericpre** [comment]
Thanks @jacobjma! The original cause of confusion was the package on conda-forge is not up to date and as mentioned [above](https://github.com/jacobjma/abTEM/issues/39#issuecomment-875010723), this may be related to the fact is the source distribution is not up to date - [the source distribution is used in the conda-forge recipe](https://github.com/conda-forge/abtem-feedstock/blob/ca9ed2a52a2a416488e6961f0581c686d771fe8c/recipe/meta.yaml#L9).

I don't know the reason but I suspect that providing the source distribution is a good practice, because the wheel doesn't contains everything available in the source distribution (doc, some metadata?) and it is not usual to make a package from a wheel, as for example in the case of conda-forge.

If the workflow works fine for the next release, you should simply need to push a tag to this repository and that's it. For conda-forge, there is also the option to [merge new release automatically](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge).
