### ISSUE TITLE
crop_to_center / _crop_to_center

### ISSUE THREAD

**Issue by geoffwoollard** [jacobjma/abTEM#4]
Line 9 and 171 in [`waves.py`](https://github.com/jacobjma/abTEM/blob/fc5df17f455ee42a45899bafc1de7be64a61fa5f/abtem/waves.py ) references `abtem.detect._crop_to_center`.
```
9: from abtem.detect import AbstractDetector, _crop_to_center
```
```
171:         pattern = asnumpy(abs2(_crop_to_center(xp.fft.fftshift(fft2(self.array, overwrite_x=False)))))

```

But there is only `crop_to_center` (without the underscore) in [`detect.py`](https://github.com/jacobjma/abTEM/blob/fc5df17f455ee42a45899bafc1de7be64a61fa5f/abtem/detect.py)

**Comment by jacobjma** [comment]
Hi Geoff,

This problem is now fixed.

Note that the developer (master) version on git can have some issues, while we are still making significant changes. The version on pip should work.

**Comment by geoffwoollard** [comment]
Ok, so the pip version is the more stable one?

**Comment by jacobjma** [comment]
Yeah, the pip version is generally more stable.
