### ISSUE TITLE
Error encountered when running abTEM with multiple GPUs 

### ISSUE THREAD

**Issue by GearoidM** [jacobjma/abTEM#42]
Dear abTEM users, 

I recently tested out some code on a [supercomputer](https://www.ichec.ie/about/infrastructure/kay) and ran into an issue when attempting to use multiple GPUs with a slightly adapted version (using an S-matrix and pixelated detector instead) of the code from [here](https://github.com/jacobjma/abTEM/blob/master/examples/parallel/multi_gpu.py). The SLURM output read: "ValueError: Array device must be same as the current device: array device = 0 while current = 1". Does anybody have any experience with using multiple GPUs?

Regards.

Gearóid.

**Comment by jacobjma** [comment]
We don't really support multiple GPUs, although it should be possible, but requires a fair bit of custom scripting using MPI.

You will most likely have to brace yourself with a bit of patience for our upcoming version, using dask, which will allow multi-cpu and multi-gpu computations.
