### ISSUE TITLE
grid view size and plot intensity of peaks, Can it read .xyz file as well?

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#43]
From the section of Multislice simulation.  I tried to run the code on Silicon.cif file.   I just followed instructions on abtem foram and obtained these results,  I have limited knowledge of python and still learning.  If you can guide me that how I can change/ control the gride size (in multislice), plot intensity of observed peaks, change of through the commands in python.

I noticed that grid is not defined in multislice .. How can I write it separately? Below are my results at 90keV.  

Also I wanted to manipultad the atoms , wanted to make my own crystal. and i read that ASE can make .xyz file, that file can run in Multislice or not ??

![2a336600-8dbd-4a22-a3e1-8e6a3affc73c](https://user-images.githubusercontent.com/60356551/124853695-51697c00-df74-11eb-939a-42144219b0ca.jpg)
![b02df212-d55b-4bba-bd2c-f84a70089352](https://user-images.githubusercontent.com/60356551/124853708-562e3000-df74-11eb-8c95-34b59197bc1c.jpg)

Regards
Syed

**Comment by TomaSusi** [comment]
Dear @hkazmi25,

Yes, ASE can read in .xyz files (https://wiki.fysik.dtu.dk/ase/ase/io/io.html), after which that structure is an `Atoms` object that can be used in abTEM. For more instructions on how to manipulate atoms using ASE, please see https://wiki.fysik.dtu.dk/ase/gettingstarted/manipulating_atoms/manipulating_atoms.html.

The grid is not separately defined but its spacing, which controlled by the `sampling` parameter of the `Potential` object: https://abtem.readthedocs.io/en/latest/walkthrough/02_potentials.html.

For help in plotting line profiles and such, standard matplotlib commands can be used, though abTEM also implements interpolation. For help you can see our example or article code, for example this notebook:
https://github.com/jacobjma/abTEM/blob/master/articles/2021_ORE_abTEM/hBN_DFT_IAM.ipynb

Best,
Toma
