### ISSUE TITLE
Diffuse scattering?

### ISSUE THREAD

**Issue by hkazmi25** [jacobjma/abTEM#47]
I would like to see diffuse scattering from ideal and manipulated crystals. would it be possible with abTEM, if yes, Can any respected Developer can help here??
Regards

**Comment by jacobjma** [comment]
I am assuming you are referring to diffuse scattering due to phonons?

We have a document in the docs on simulating thermal diffuse scattering.
https://abtem.readthedocs.io/en/latest/walkthrough/08_temperature.html

Our quickstart examples also provide some help (look to the code that is commented out):
https://github.com/jacobjma/abTEM/blob/master/examples/quickstart/quick_hrtem_and_saed.ipynb

**Comment by hkazmi25** [comment]
Thankyou Jacob.. I will see and update you about it.

**Comment by hkazmi25** [comment]
Hello Jacob

An update about the diffuse scattering problem. 
1) by making simple cubic structure one can see the diffuse scattering but the problem with the output is .. I see  the background noise very much. I don't understand what is it, also can you have any solution to filter out the diffuse scattering peaks from braggs diffraction peaks. 
in this figure (any ideal bcc lattice structure) below you see white background in center and its more pixelated image, can you suggest something to get better outputs. and how i can see diffuse pattren more clearly. ?

![diffuse scatt_1](https://user-images.githubusercontent.com/60356551/130816305-fcdf5f4e-2bde-4cdc-ae7c-e13531ed9028.png)

2) is abTEM FroznPhonon calculation only works for cubic lattices? In the following program i am getting the error. how should i correct this one. I am trying the elements from CIF file. 

`from abtem.potentials import Potential
from abtem import PlaneWave, FrozenPhonons
from ase.io import read
import matplotlib.pyplot as plt
import matplotlib.colors 
from ase import Atoms
from ase.build import hcp0001, hcp10m10
from ase.visualize import view
from abtem.measure import block_zeroth_order_spot
import numpy as np

wave = PlaneWave(energy= 90e3, sampling=0.06)

Vo2 = read('/home/siwi2-ubuntu/Documents/abtem 1/CIF/VO2_mp-1021522_MONO.cif')


frozen_phonons = FrozenPhonons(Vo2, 512,{'V':0.2,'V0':0.2,'O':0.2}, seed=1)
atoms_conf = next(iter(frozen_phonons))

#view(atoms_conf)

#potential = Potential(frozen_phonons, gpts=512, slice_thickness=5, projection='infinite', parametrization='kirkland')

exit_waves = wave.multislice(Vo2)

aa=exit_waves.write('/home/siwick2-ubuntu/Documents/abtem 1/Phonons/VO2_Mono.hdf5')

bb=exit_waves.show(aa)

diff_pat = exit_waves.diffraction_pattern(aa)

e_diff= block_zeroth_order_spot(diff_pat)

ax, image= diff_pat.show(power = 1, figsize = (6,6), cmap='RdBu_r')

plt.colorbar(image,  orientation = 'vertical')

ax.set_xlim([-100,100])
ax.set_ylim([-100,100])
plt.show()`
  
The error is 
`(base) siwick2-ubuntu@siwick2ubuntu:~$ /home/siwi2-ubuntu/anaconda3/bin/python "/home/siwick2-ubuntu/Documents/abtem 1/Phonons/VO2.py"
Traceback (most recent call last):
  File "/home/siwick2-ubuntu/Documents/abtem 1/Phonons/VO2.py", line 31, in <module>
    exit_waves = wave.multislice(Vo2)
  File "/home/siwick2-ubuntu/anaconda3/lib/python3.8/site-packages/abtem/waves.py", line 507, in multislice
    potential = Potential(atoms=potential)
  File "/home/siwick2-ubuntu/anaconda3/lib/python3.8/site-packages/abtem/potentials.py", line 508, in __init__
    raise RuntimeError('Atoms are not orthogonal')`
