### ISSUE TITLE
Help tuning ePIE parameters for low dose 4DSTEM data

### ISSUE THREAD

**Issue by GearoidM** [jacobjma/abTEM#48]
Dear users and authors, 

I am wondering if anyone has any advice on how to tune the parameters of ePIE for phase recovery from low dose diffraction data. I have seen papers (here is an [example](https://www.nature.com/articles/s41467-020-16391-6)) where they used doses as low as 5.7 e / A**2 when recording real 4DSTEM datasets and managed to get fantastic looking reconstructions using the ePIE.

For context, here is some experimental information that could be relevant:

1. We are simulating a 4DSTEM experiment with an iron nanoparticle embedded in ice. The lattice parameters of the nanoparticle are a=b=c = 18 A and alpha=beta=gamma=90°. All sides are surrounded by about 11 A of ice, such that the effective dimensions of the input structure file are 40 x 40 x 40 A**3. 
2. We have tuned the 4DSTEM experimental parameters to ensure that the overlap of the scanning probes is 86 %.  
3. We record 3844 patterns in a 40 x 40 A**2 area. Each pattern has 182 x 182 pixels**2, with a maximum detection angle of approximately 95 mrad. 
4. The size of the ePIE reconstruction is also 182 x 182 pixels**2. 
5. For the images we provided, we ran the ePIE 50 times. We tested for alpha set to 1 and 0.05, while choosing not to update the probe -the probe guess was the one used in the simulation- to reduce the number of tunable parameters. 

In Fig. 1 and Fig. 2, I provide examples of the results we have obtained using different doses, alpha values and iterations. When low dose conditions are simulated, setting alpha to 0.05 results in a somewhat better reconstruction than using an alpha set to 1 (see Fig. 2). Conversely, an alpha of 1 appears better than an alpha of 0.05 for high dose experiments (see Fig. 1).

We have tried several other values for alpha (and beta, before deciding to not update the probe) and we have tried increasing the number of iterations to 1000, too, and have not seen any obvious changes in the images. I note that it is possible that a 'better' reconstruction might come after many more iterations. However, I would expect that 1000 would be sufficient, considering the authors of this [paper](https://www.nature.com/articles/s41467-020-16391-6) managed to get objectively clear reconstructions from real low-dose cryo-data within 300 iterations. 

Furthermore, I have also added [rPIE](https://www.osapublishing.org/optica/fulltext.cfm?uri=optica-4-7-736&id=368463) to my own installation of abTEM and the results are about the same or sometimes worse when alpha is too low ( < 0.05). 

Can anyone comment on the results? Can I tune the parameters of ePIE to get a better reconstruction? And can anyone share how they choose initial guesses for alpha, beta and the number of iterations?

![infinite dose alpha 1](https://user-images.githubusercontent.com/36663477/130334705-70315803-2c0c-498d-abbd-1a4481e2faea.png)

![infinite dose alpha 0 05](https://user-images.githubusercontent.com/36663477/130334710-b68789f6-3ff9-4817-9582-fd1d8b7b4990.png)
Fig. 1: Reconstruction with low dose turned off: (top) alpha = 1 and (bottom) alpha = 0.05. The probe was not updated at any of the 50 iterations. 

![200 e per A sq alpha 1](https://user-images.githubusercontent.com/36663477/130334748-9e889add-8a0c-45ed-8330-61ef9b28e7c4.png)
![200 e per A sq alpha 0 05](https://user-images.githubusercontent.com/36663477/130334751-834586c8-69cb-4e9a-a026-ac4d5d4bdc10.png)
Fig. 2: Reconstruction with low dose turned **on** (200 e / A**2): (top) alpha = 1 and (bottom) alpha = 0.05. The probe was not updated at any of the 50 iterations.

**Comment by GearoidM** [comment]
I realised that low dose limits resolution so comparing the images in Fig 1 and 2 to those in this [paper](https://www.nature.com/articles/s41467-020-16391-6) is not fair given the difference in scale, and I am unlikely to get better results without using some kind of Fourier filtering. Though it would still be helpful to me (and maybe others) if someone could share their insight into choosing ePIE parameters. Is it just trial and error or is there a way to choose an initial guess depending on the data?

**Comment by jacobjma** [comment]
I have to admit that I am not an expert on 4D-STEM, I only implemented ePIE for one paper, using only simulated data. I have been thinking about contributing the ePIE algorithm to Py4DSTEM, given that it is somewhat out-of-scope for abTEM and the Py4DSTEM community might be better at answering these issues.

> Furthermore, I have also added rPIE to my own installation of abTEM
That's awesome.

> Is it just trial and error or is there a way to choose an initial guess depending on the data?
I would love to tell you, but at this point, you probably know more than me.

**Comment by GearoidM** [comment]
Okay. Thank you for your response!
