### ISSUE TITLE
sample rotate

### ISSUE THREAD

**Issue by yc9690** [jacobjma/abTEM#49]
Hello. i have a small question for your help. After I tilt the sample from (001) to (110) or other direction with defining "rotate_cell=True" , why there is an error, like "Atoms are not orthogonal", when i want to get the potential of atoms.

If I define "rotate_cell=False", the potential function is ok. But i check the region of gridscan by the following code, which is not where I am interest. Do you konw what is the problem of my runing.  Thanks a lot.

ax, im = potential.project().show();
gridscan.add_to_mpl_plot(ax)

**Comment by TomaSusi** [comment]
Which "sample"? What is your atoms object? Is it orthogonal to start with? Can you get the potential of the non-rotated cell?

**Comment by yc9690** [comment]
Hi. i use a (8, 3, 1) SrTiO3 supercell created from VESTA.  If i do not rotate the supercell, i can get the potential. But if i tilt the supercell from (001) to (110) or other direction with defining "rotate_cell=True", there is an error,  "Atoms are not orthogonal", when i want to get the potential of atoms.

**Comment by TomaSusi** [comment]
Thanks for the clarification. Could you try using the `abtem.structures.orthogonalize_cell` function after rotating the cell?

**Comment by yc9690** [comment]
I just tried this function, but show an error "cannot convert Infinity to integer ratio".

**Comment by jacobjma** [comment]
The `orthgonalize_cell` function is not smart enough to make any cell orthogonal.

You should instead use the surface function to rotate the atoms as below (the crystal function is not important here, it just creates the SrTiO3 structure):
```
from ase.spacegroup import crystal
from ase.build import surface

atom_pos = [(0.0, 0.0, 0.0), (0.5, 0.5, 0.5), (0.5, 0.5, 0.0)]
srtio3_100 = crystal(['Sr','Ti','O'], atom_pos, spacegroup=221, cellpar=3.905, size=(2, 2, 2))

srtio3_110 = surface(srtio3_100, (1,1,0), layers=4)
srtio3_110.center(axis=2, vacuum=2)

fig, (ax1, ax2) = plt.subplots(1, 2)
show_atoms(srtio3_110, ax=ax1, plane='xy', title='top view')
show_atoms(srtio3_110, ax=ax2, plane='xz', title='side view')
```

More info:
- https://wiki.fysik.dtu.dk/ase/ase/build/surface.html?highlight=cut#create-specific-non-common-surfaces
- https://wiki.fysik.dtu.dk/ase/_downloads/2f0891a3474a835408631adfec1651d7/general_surface.pdf

**Comment by jacobjma** [comment]
Questions related to non-orthogonal cell seems to be one of the most common. We may need to create a documentation page dedicated to this.

**Comment by yc9690** [comment]
Thanks a lot for these explanations.  I checked the “surface” function. it cannot rotate the super-cell i already created from VESTA.  the indices parameter in  "surface” function doesn"t work for the super-cell I defined. Do you know the some way to solve it.

**Comment by jacobjma** [comment]
I don't know. Could you send the structure file? I believe you can drag and drop it into the comment form here.

**Comment by TomaSusi** [comment]
You cannot use the `surface` function to manipulate a cell you have created by other means, it is for creating a structure.

Can you try to replace the `size=(2,2,2)` in the code Jacob posted with `size=(8,3,1)` (or some other ordering of the indices)? Or use `size=(1,1,1)` and then replace the `(1,1,0)` in the `surface` function below with `(8,3,1)`?

**Comment by yc9690** [comment]
It works for the supercell created by crystal function no matter how i change the size.  

It doesn't work for the supercell I created by VESTA. There is no indices information.  But actually I would like to define a supercell from ADF or ABF image, which is not a perfect structure that can be created by this crystal function i guess.  This (8, 3, 1) SrTiO3 supercell is just a test structure i created. Do you some ways to define the indices information of a super-cell created by other methods.

**Comment by yc9690** [comment]
Or if there is a way to enlarge the gridscan area rather than only the region of the supercell when defining "rotate_cell=False"

**Comment by jacobjma** [comment]
> Or if there is a way to enlarge the gridscan area rather than only the region of the supercell when defining "rotate_cell=False"
No, the multislice algorithm requires an orthogonal supercell aligned with the propagation direction. It is not trivial, or even necessarily possible, to do this for all cells while simultaneously fulfilling the requirements of periodic boundary conditions.

If you rotate the atoms without changing the unit cell (i.e. setting `rotate_cell=False`), the resulting structure will almost certainly not be periodic. 

If it is not possible to fulfill periodicity you may need to create a big enough slab of the structure, such that the periodic boundary conditions are not felt in the region of the potential where the gridscan is performed.

There is not any easy way of doing this currently, although this is something I want to work on. However, the links below might help:
- https://github.com/jacobjma/abTEM/issues/25
- https://github.com/jacobjma/abTEM/blob/master/examples/other/simulating_non-periodic_structures.ipynb

**Comment by yc9690** [comment]
Thanks a lot for your help. It works fine.

**Comment by jacobjma** [comment]
What works fine?

**Comment by yc9690** [comment]
After rotate with defining "rotate_cell=False", the probe can scan at the region I am interest. That is what I want.

**Comment by yc9690** [comment]
it works fine only for my test supercell where there is no gap between the repeated single cell  when i use atoms *= (x,y,z) to enlarge the supercell. when i define a structure, and use atoms *= (x,y,z) to enlarge the supercell, there is a gap between the repeated single supercell. I don't know how to remove it.

**Comment by TomaSusi** [comment]
You cannot rotate a structure with `rotate_cell=False` and then multiply it, that is not a periodic structure. I do suggest you to find a way to define your structure using ASE instead of using an external program, but this is overall not really an abTEM issue any longer.
