### ISSUE TITLE
measure.py and noise.py: using the Calibrations object and Measurement Object in order to add noise to detected wave

### ISSUE THREAD

**Issue by danielkangell** [jacobjma/abTEM#5]
Awesome project - really enjoying abtem and all the new features/documentation, so thank you!

I am trying to implement my old pyqstem code, and am struggling to resample and add noise to my exit_wave.

I see that poisson_noise takes a Measurement object as its input. So I am trying to make a Measurement object using my exit_wave.intensity(), and a Calibration object. 

Somewhere I am going wrong, because my measurement object array property is an array of measurement objects, not floats. This throws an error when trying to use poisson_noise as it tries to divide a measurement object:

<img width="1007" alt="Screen Shot 2020-10-14 at 10 46 02 AM" src="https://user-images.githubusercontent.com/36577697/96025789-7d533900-0e0a-11eb-97d8-fe259397c711.png">

I'm sure I am making an error somewhere but I am having trouble finding it. Maybe an example of resampling and dosage would help! Thanks again

**Comment by jacobjma** [comment]
Hi Daniel,

Thanks. The intensity method should already return a measurement object with the correct calibrations.

I added a cell in one of the examples, that adds noise to a HRTEM image.

https://github.com/jacobjma/abTEM/blob/master/examples/basic_hrtem_and_saed.ipynb

Note that a new pypi version of abTEM was just created today.

**Comment by danielkangell** [comment]
Awesome, thank you so much!
