### ISSUE TITLE
PixelatedDetector setting

### ISSUE THREAD

**Issue by yc9690** [jacobjma/abTEM#51]
Hello. I have a small question. For 4dstem simulation, the "semiangle_cutoff" in Probe function i used is 20 mrad, that is the convergent angle if I understand it correctly. But when i define "max_angle" in PixelatedDetector as 100 mard, it show me an error that the max_angle is larger than max scattering angle. but how could i change the max angle of the PixelatedDetector. If i use  "valid"  rather than  100 mrad, the detector is only 4 mrad when i check the pacbed pattern. Could you help me what is wrong with my setting. Thank you.

**Comment by jacobjma** [comment]
You have to improve the sampling of your simulation. The maximum _possible_ detected angle is not determined by the probe-forming aperture, but by the real-space sampling of your probe. This is not a physical parameter, however, to solve the problem using FFTs, you have to discretize it. Please read the "Real-space sampling" section of this link
https://abtem.readthedocs.io/en/latest/walkthrough/03_wave_functions.html

Write again if it is still not clear.
