### ISSUE TITLE
Defocus setting for STEM simulation

### ISSUE THREAD

**Issue by luoye029** [jacobjma/abTEM#56]
Hello, I am a user of abtem, very thanks for your effort. I am writing to ask you a question about "defocus setting" for STEM simulation. I am curious that where probe locates at when I set zero as defocus, is it the top of specimen structure or bottom plane of specimen structure? How to set defocus value if I want to set defous at the middle of model, for example, I have structure with 10nm, should defocus-setting be -5 nm or 5 nm if I want to set defous at the middle of model. Thanks for your reply.

**Comment by jacobjma** [comment]
Positive defocus is equivalent to backward free-space propagation, I copied the following from a test:

```
from abtem.waves import FresnelPropagator, Probe
import matplotlib.pyplot as plt
 
propagator = FresnelPropagator()
 
probe1 = Probe(extent=10, gpts=256, energy=80e3, semiangle_cutoff=80).build()
 
probe2 = probe1.apply_ctf(defocus=50) # apply a defocus of 50 Å (equivalent to C10=-50)
 
probe3 = propagator.propagate(probe1, dz=-50, in_place=False) # propagate 50 Å backwards
 
probe4 = propagator.propagate(probe2, dz=50, in_place=False) # propagate 50 Å
 
fig,(ax1,ax2,ax3,ax4)=plt.subplots(1, 4, figsize=(12,6))
probe1.show(ax=ax1, title='Initial')
probe2.show(ax=ax2, title='Aberrated')
probe3.show(ax=ax3, title='Back-propagated');
probe4.show(ax=ax4, title='Aberrated and forward-propagated');
```
![billede](https://user-images.githubusercontent.com/17334286/133617712-bd45b3be-768d-4289-b109-234a84407125.png)
`probe2` and `probe3` are identical, so are `probe1` and `probe4`. I guess you can say that the defocus is defined relative to the entrance plane, however, depending on the Cs, the probe might be smaller at some other position along the optical axis.

As a sidenote, the defocus is by convention, but annoyingly, defined as negative C10, i.e., this should hold true for some wave function `exit_wave`.
```
np.all(exit_wave.apply_ctf(C10=-100).array == exit_wave.apply_ctf(defocus=100).array)
```
