### ISSUE TITLE
display the complex number with original magnitude and phase

### ISSUE THREAD

**Issue by zezhong-zhang** [jacobjma/abTEM#58]
For displaying the complex number, the current `domain_coloring` function convert the complex value to RGB values and hence the colorbar added for `plt.imshow` loses their meaning for their orginal magnitude or phase. I am wondering if can still make the colorbar meaningful, for instance similar to [cplot](https://github.com/nschloe/cplot), which is useful for showing the wave function or EELS potential.

**Comment by jacobjma** [comment]
Not right now, you would have to make your own custom plots from the numpy array.

However, thank you for making me aware of cplot, I have been looking for something like that. It should be fairly harmless to add cplot as a dependency and use their implementation instead of our own.

**Comment by zezhong-zhang** [comment]
Yes, I implemented a temporary solution to display the absolute value (with log scaling) and a phase colour wheel. It is not ideal though as adding a subplot for the colour wheel to the existing subplot in the axes, fig is tricky, so need to adjust the figure size without overlaps.
