### ISSUE TITLE
Minor issue with setting the sampling

### ISSUE THREAD

**Issue by cophus** [jacobjma/abTEM#60]
A user tried to run a 4D-STEM simulation with settings like so:

```
probe = abtem.Probe(gpts=(1024,1024), energy=80e3, semiangle_cutoff=25, defocus=-1*def_val)
potential = abtem.Potential(model, sampling=0.05, parametrization='lobato')
... etc.
```

When they then tried to change the cell size (in model.cell), the sampling value was overridden.  I am pretty sure this is due to the conflict between these 3 values:
```
gpts=(1024,1024)
sampling=0.05
model.cell
```
Because only 2 of these 3 values can be free parameters.  Suggested fix:  throw a warning if the user specifies incompatible dimensions / sampling.

**Comment by TomaSusi** [comment]
What do you mean by "change the cell size"? `atoms.set_cell(..., scale_atoms=True)`, or..?

**Comment by M0hsend** [comment]
Hi @TomaSusi  I was doing something like `model = graphene.repeat((3,3,1))` and then increasing the repeat number.

**Comment by TomaSusi** [comment]
Oh so you are changing the supercell size, I see. Well, in any case, the `Potential` function ALWAYS tries to pick a sampling that is as close as possible to the specified sampling, but it will need to adapt it to make the numerical grid commensurate with the cell.

**Comment by TomaSusi** [comment]
Normally, we would set the sampling only for the potential and not specify the probe `gpts` by hand, though perhaps you're doing PRISM and this is desirable?

**Comment by M0hsend** [comment]
I was doing the following for the probe:
`probe = abtem.Probe(gpts=(1024,1024), energy=80e3, semiangle_cutoff=25, defocus=-1*def_val)`
Not using PRISM. Just overlooked that I am assigning different values to the same parameter.

**Comment by TomaSusi** [comment]
Right, well if you look at our walkthroughs, we typically don't give the probe gpts explicitly, ie. in your case:

`probe = abtem.Probe(energy=80e3, semiangle_cutoff=25, defocus=-1*def_val)`

and everything should automagically work.

**Comment by TomaSusi** [comment]
But yeah, maybe it @jacobjma would be good to throw a warning whenever the sampling is automatically adapted (perhaps beyond some tolerance?)

**Comment by M0hsend** [comment]
Many thanks for this great library by the way @TomaSusi et al.

**Comment by jacobjma** [comment]
Yes, I think it is a good idea to warn users when the simulation grid is overspecified and inconsistent.

The code below will now throw a warning:
```
from abtem import Probe, Potential
from ase import Atoms

probe = Probe(gpts=1024, energy=80e3, semiangle_cutoff=25)
potential = Potential(Atoms(cell=(10,)*3), sampling=.1, parametrization='lobato')

probe.grid.match(potential)
```
```
UserWarning: Overspecified simulation grid gpts ((1024, 1024) != (200, 200))
```

The `grid.match` method is used inside all other relevant methods such as `scan` and `multislice`.

**Comment by TomaSusi** [comment]
All right, that seems like a good place to close this issue.
