### ISSUE TITLE
SMatrix interpolation

### ISSUE THREAD

**Issue by erh3cq** [jacobjma/abTEM#62]
I noticed in the documentation that SMatrix interpolation allows for a tuple, but the code does not allow for it (see below). How do we use the tuple? At the least, this is a documentation alert!

[https://github.com/jacobjma/abTEM/blob/c302a285bb7266659288e0ec5e6e2442cc1cb437/abtem/waves.py#L1736](https://github.com/jacobjma/abTEM/blob/c302a285bb7266659288e0ec5e6e2442cc1cb437/abtem/waves.py#L1736)

**Comment by jacobjma** [comment]
I checked it, you are right, this is a bug. Thanks for reporting. I will fix this tomorrow.

**Comment by jacobjma** [comment]
I got it fixed. You can now correctly use a tuple for the interpolation factor.
