### ISSUE TITLE
Issue on Ag [111] HRTEM image simulation

### ISSUE THREAD

**Issue by JulioAzcarate** [jacobjma/abTEM#81]
Hi Jacob and Toma

First, thank you for your work and congratulation!... `abTEM` is wonderfull. I'm "playing" from old versions of pyQSTEM.

Now, I'm working on HRTEM image simulation of stacking faults in Ag {111} planes imaging it along [111] axis zone. 
Experimentally, I'm using a Tecnai G2 F20 Ultra-Twin with Schotky-Field Emission gun (Energy = 200keV, Energy spread = 0.8 eV, Cs = 0.5mm, Cc = 1.2mm, Lens stability = 5 ppm, Voltage stability = 5 ppm, the point resolution is 0.19nm).

My early work was started on simulations using `JEMS`. I start just with a bulk crystal without stacking faulst. When I simulate a bulk crystal of FCC Ag along [111] axis zone, is obtained the expected _"plain gray image without lattice fringes"_ because the plane separation of {220} planes is 0.142nm.

However, when I try to simulate the same model with `abTEM`, a hexagonal lattice fringes is obtained. Even, using a higher value of Cs (1mm, with point resolution 0.23nm) also an hexagonal lattice fringes are obtained. 

I don't understand what I'm doing wrong. Any advise?

This is my code:

```python
from abtem import __version__
print('current version:', __version__)

import numpy as np

from ase.io import read
from ase import Atoms

from abtem.visualize import show_atoms
from abtem.transfer import CTF, scherzer_defocus, point_resolution, energy2wavelength
from abtem.structures import orthogonalize_cell

import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True

from abtem import *
```
The Microscope conditions
```python
# Microscope conditions
# Tecnai G2 F20 UT-FE

energy=200e3           # eV
Cs = 1                 # 0.5 mm
Cc = 1.2               # 1 mm
dE = 0.8               # eV
dI = 5                 # ppm
dV = 5                 # ppm

# ----------------------------------------
# as abTEM use Å, the convertion is nedeed
cs = -Cs * 1e-3 * 1e10    # in Å
cc = Cc * 1e-3 * 1e10    # in Å
# ----------------------------------------

focal_spread = cc * np.sqrt( 4*(dI*1e-6)**2 + (dE/energy)**2 + (dV*1e-6)**2 )

ctf = CTF(Cs=cs, energy=energy)
ctf.defocus = scherzer_defocus(cs, ctf.energy)
ctf.point_res = point_resolution(cs, ctf.energy)
ctf.long = energy2wavelength(ctf.energy)

print("CTF defocus: {:.1f} Å".format(ctf.defocus))
print("CTF point resolution: {:.1f} Å".format(ctf.point_res))
print(focal_spread)
```
Creating the model
```python
from ase.build import fcc111
slab = orthogonalize_cell(
    fcc111('Ag', 
           size=(1,1,13), 
           vacuum=5.0,
          )
    )

fig, axs = plt.subplots(1,3, figsize=(15,7))
#plt.subplots_adjust(wspace=0.02)

show_atoms(slab, ax=axs[0], plane='xy')
show_atoms(slab, ax=axs[1], plane='xz')
show_atoms(slab, ax=axs[2], plane='yz')
```
Simulation
```python
potential = Potential(slab, 
                      gpts=512, 
                      slice_thickness=0.5, 
                      parametrization='kirkland', 
                      projection='infinite')

wave = PlaneWave(
    energy=energy # acceleration voltage in eV
)

exit_wave = wave.multislice(potential)

ctf = CTF(
    energy = energy,
    semiangle_cutoff = 20, # mrad <--- Apertura Objetivo
    focal_spread = focal_spread, # Å
    defocus = ctf.defocus, # Å
    Cs = cs # Å
)

image_wave = exit_wave.apply_ctf(ctf)

image_wave.intensity().mean(0).tile((3,2)).show();
```

**Comment by jacobjma** [comment]
Thank you!

You should still expect to have contrast beyond the point resolution, it will just be small. To completely kill all fringes under the point resolution you need to actually set the aperture to match the crossover point.

If you add a colorbar or add some realistic noise, it will be quite obvious that the contrast you are getting with your current parameters is tiny. I don't know what is happening in JEMS, maybe you are just not showing the full range of grayscale values?

Using your parameters and a dose of $10^7 \ e^{-1} / \mathrm{Å} ^2$, I get an image like this.
```python
from abtem.noise import poisson_noise

image = image_wave.intensity()
poisson_noise(image, dose=1e7).show()
```
![noise](https://user-images.githubusercontent.com/17334286/171031617-62961503-fbc1-4114-84e6-3ae5adb06500.png)

**Comment by JulioAzcarate** [comment]
Dear Jacob

Thank you so much for your very fast anwser!!! ... 
I guess `JEMS` probably use some electron dose by default which I can't change. It isn't a simple grey scale reason, because no fringes are observed by changing brightness, contrast or gamma.

You response is clear and very convincent. Thank you so much!

_For that reasons, I love the open source software_

Regards

**Comment by JulioAzcarate** [comment]
Dear Jacob

I solve the problem!.
The issue was the convergence angle. I just noted that `JEMS` assume a great convergence by default, affecting drastically the spatial coherence, killing {220} reflections. 
The best conclusion is: "all it's OK with `abTEM`"

Thank you so much for your time, and thank you again for this excelent software!!!

Regards
