### ISSUE TITLE
CFT plot - X axis in reciprocal space

### ISSUE THREAD

**Issue by JulioAzcarate** [jacobjma/abTEM#82]
Hi Jacob and Toma

Is there any way to plot the CTF in reciprocal space ($A^{-1}$ or $nm^{-1}$)?
The x axis is actually in $2\theta$ units?

Thanks in advance

**Comment by EthanJUCB** [comment]
It would be great to have this flag in CTF.

**Comment by jacobjma** [comment]
There was not, however, I just added an argument to the `.show` method for doing this. You need to install the development version for now.

```python
ctf = CTF(energy=200e3, defocus=100)
ctf.show(reciprocal_units=True)
``` 

If you need more control over the plot. You can always get the CTF profiles, then grab the array and make your own plot.
```python
ctf = CTF(energy=200e3, defocus=100)
profiles = ctf.profiles(reciprocal_units=True) # -> dict with item for each "component" of the CTF

profiles['ctf'].array
sampling = profiles['ctf'].calibrations[0].sampling # sampling rate of the array in 1 / Å
```

**Comment by JulioAzcarate** [comment]
Great!!! ... Thank you so much Jacob.
